application:
  port: 8000
database:
  host: '127.0.0.1'
  port: 5432
  username: 'postgres'
  password: 'password'
  database_name: 'newsletter'
email_client:
  # Value retrieved from Postmark's API documentation
  base_url: 'https://api.postmarkapp.com'
  # Use the single sender email you authorised on Postmark!
  sender_email: 'idris.khan@howdens.com'
